### ISSUE TITLE
dataset format

### ISSUE THREAD

**Issue by trungpham2606** [ahq1993/MPNet#10]
@ahq1993 
Tks for sharing such a great work.
It seems that libbot2 is not supported on Windows.
So can you please explain for me the format of the dataset after getting through all steps in data generation ? 
I will try to generate the dataset by myself after knowing thoroughly the format of needed dataset.

**Comment by ahq1993** [comment]
Follow the updated instructions on the GitHub. I have also released a simple python-based visualizer.
