### ISSUE TITLE
Hi, could you let me know what observations were used in 7 DOF robot environment?

### ISSUE THREAD

**Issue by minsungyoon** [ahq1993/MPNet#11]
I think that the joint's angle and velocity and link's position and velocity(transitional and rotational)  are usually used in a manipulation task.

I want to know which information is considered to the input of the neural network ( without the feature Z from the environment's cloud points ).

Thanks for your kind response in advance ^ ^!

**Comment by ahq1993** [comment]
In the case of simple 2D, complex 2D/3D, and rigid body, we create a point-cloud by sampling the obstacle space from a known environment. In the case of Baxter, the point-cloud is from a depth sensor. You can further process your point-cloud into voxel and use 3D-CNN for encoding. Please follow the updated instruction on the github!
