### ISSUE TITLE
What is the point cloud data given to the network?

### ISSUE THREAD

**Issue by rajathkmanjunath** [ahq1993/MPNet#12]
Hi Ahmed,

I think you have done a great job in the field of Path Planning. 
I read your paper and was wondering what was the point cloud data that was fed to the ENet. was it the point cloud data from a sensor at the end effector or any other position or is it the point cloud data that you generate for a known environment. You don't talk about the details of the data in the paper.
what kind of data did point cloud data did you use?

**Comment by ahq1993** [comment]
In the case of simple 2D, complex 2D/3D, and rigid body, we create a point-cloud by sampling the obstacle space from a known environment. In the case of Baxter, the point-cloud is from a depth sensor. You can further process your point-cloud into voxel and use 3D-CNN for encoding.
