### ISSUE TITLE
Viewer can not be opened

### ISSUE THREAD

**Issue by MzXuan** [ahq1993/MPNet#2]
Hi, Thanks for your code.

Can you explain in more detail how to run the `main_viewer` and `rrts_main`?

After I successfully build the data_generation, I have got `viewer` in `data_generation/viewer/build/bin/` and `rrtstar` in `data_generation/build/bin/`. However, when I try to run them, the terminal gives me `./viewer: error while loading shared libraries: libbot2-vis.so.1: cannot open shared object file: No such file or directory`
`./rrtstar: error while loading shared libraries: libbot2-core.so.1: cannot open shared object file: No such file or directory`

Could you help me with it? Is there any parameter I should send to the script?

Thanks for your help.

**Comment by MzXuan** [comment]
Hi, we solve the last problem. However, our trajectory generation seems does not work well. We can not see a complete trajectory from the viewer. 
The viewer shows trajectory generation procedure as follows,
![1111](https://user-images.githubusercontent.com/13446254/48909030-168ba600-eea7-11e8-94be-8d5af9e4f150.png)
And the recorded result in the file below.
[2018-11-22-viewer.03.ppms.gz](https://github.com/ahq1993/MPNet/files/2608436/2018-11-22-viewer.03.ppms.gz)

Here is our [code](https://github.com/MzXuan/MPNet) to generate trajectories.

Thanks for your help.

**Comment by deviprasad97** [comment]
I am having the same problem. would you be able to explain how to generate data after successful compilation.

**Comment by hynkis** [comment]
In my case, the files, "libbot2-core.so.1" and  "libbot2-vis.so.1" are in the directory, "/usr/local/lib".
After make in "data_generation", I copied the two files and pasted in "data_generation/build/lib".
Then I could run "rrtstar" and "viewer".
